apiVersion: v1
kind: Secret
metadata:
  name: card-secret
type: Opaque
data:
  cardBillBondPrivatekey=MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJIcWzGOK3Pn2JeCT6iLZNg2LJXdZR43CSZBRQsyy+zuBV3AizNPK8y+ONFdjP8VwuHkeZqrae76z7pH/m/B+g+PlQJ/tI3Qv77S+pr9yq/FvHNXPrK6J60SYsQQiUDrEY25A3R1JVXytjAaEwcTW/nWuEKnY6xHsMuk2KtrFCbNAgMBAAECgYBB+4RDUMzWvvDVGwgWOT0FVxGzbBPqHTiIihlAAWSOTr8lo3o5ZZuGDrFh+zldSNqFYMR50Mc6IRIGMdT5a0Qda9O28ah1XND7bt0RwytFYrFwRlILgo5kDEAsGk2ZVwCZFBxDdTN3OjX1ic7bUb2Ea3unR7C8e2IuTt22B622kQJBAM44cqPDoOz259WKoo+9O5a0wLq0XFHr6JGoelFyTZxVAjFD2920vZhfsYucfheRdULG8qjcGxIh3dR+otmPtOsCQQC1YWHC08RCW9C6llXqQUdcVKfItB4b5BroslPCQhBvWMtt0mv6/cGmYHYMDhH098FKfNyuOXmlZQyZIY9JNQUnAkBifhla2AOTSfW+SuGLb2D3gMsQITZ6tga1Eteg8Mvan8tVRkjLohhvnzzIJm0eyo1L4INjXQTc6yns5LLY4EcTAkAtapbqC9CGtSrMrbwRjgrqSaBBlyg636EFRzHF4HjxCJDXjOrQzB1jJaApYJSKfEb/+cfgMDAPg//lkAuqzwXdAkBfLnQemLv7QaLsDproHUxaRxvEbj9ci7Qsry29rpLQYFtvoWacXiHTjff2dLXGVTCsu0flxsCqoaWplTXOUQCc
  cardBillBondPublickey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSHFsxjitz59iXgk+oi2TYNiyV3WUeNwkmQUULMsvs7gVdwIszTyvMvjjRXYz/FcLh5Hmaq2nu+s+6R/5vwfoPj5UCf7SN0L++0vqa/cqvxbxzVz6yuietEmLEEIlA6xGNuQN0dSVV8rYwGhMHE1v51rhCp2OsR7DLpNiraxQmzQIDAQAB
  cardBillBondAesSaltKey=JXO8tTU7Ig
  cardBillBondAeskey=YtRNu0eD1dLQr/u/pb6AMw==
  cardBillBondVectorKey=Szn21EI2KlJZv9WZ
