apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpsmyservice
spec:
  gateways:
    - httpsmyservice
  hosts:
    - httpsmyservice.cncamp.io
  http:
    - match:
        - port: 443
      route:
        - destination:
            host: myservice.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpsmyservice
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - httpsmyservice.cncamp.io
      port:
        name: httpsmyservice
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: cncamp-credential